server:
  port: 8080

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_DOMAIN}
          audiences: ${AUTH0_AUDIENCE}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=${app.api-prefix}/products/**,${app.api-prefix}/categories/**
              filters:
                - StripPrefix=2
            - id: cart-service
              uri: lb://cart-service
              predicates:
                - Path=${app.api-prefix}/carts/**
              filters:
                - StripPrefix=2
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=${app.api-prefix}/orders/**
              filters:
                - StripPrefix=2

springdoc:
  swagger-ui:
    urls:
      - name: product-service
        url: /api/v1/products/v3/api-docs
      - name: cart-service
        url: /api/v1/carts/v3/api-docs
      - name: order-service
        url: /api/v1/orders/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true